"""Backend protocol for TurboQuant+.

Defines the typing.Protocol that both NumPy and MLX backends must satisfy.
"""

from typing import Protocol, runtime_checkable
import numpy as np


@runtime_checkable
class ArrayLike(Protocol):
    """Minimal array protocol for backend interop."""
    @property
    def shape(self) -> tuple: ...
    @property
    def dtype(self): ...
    def __getitem__(self, key): ...
    def __matmul__(self, other): ...


@runtime_checkable
class Backend(Protocol):
    """Backend protocol for TurboQuant operations."""
    name: str

    def array(self, data, dtype=None) -> ArrayLike: ...
    def zeros(self, shape, dtype=None) -> ArrayLike: ...
    def ones(self, shape, dtype=None) -> ArrayLike: ...
    def randn(self, shape, seed: int = 0) -> ArrayLike: ...
    def sign(self, x) -> ArrayLike: ...
    def abs(self, x) -> ArrayLike: ...
    def norm(self, x, axis=None) -> ArrayLike: ...
    def searchsorted(self, a, v) -> ArrayLike: ...
    def qr(self, x) -> tuple: ...
    def matmul(self, a, b) -> ArrayLike: ...
    def where(self, condition, x, y) -> ArrayLike: ...
    def to_numpy(self, x) -> np.ndarray: ...
    def from_numpy(self, x) -> ArrayLike: ...
    def eval(self, *args) -> None: ...
    def fast_hadamard(self, x) -> ArrayLike: ...
